# Generated by Django 6.0.2 on 2026-02-13 00:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bureau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_bureau', models.CharField(choices=[('box', 'Box office'), ('cloisonne', 'Cloisonné'), ('open', 'Open Office'), ('entier', 'Entier')], max_length=100, verbose_name='Type de bureau')),
                ('nom', models.CharField(blank=True, default='', max_length=100, verbose_name='Nom')),
                ('niveau', models.CharField(blank=True, default='', help_text='Étage ou niveau du bureau', max_length=100, verbose_name='Niveau')),
                ('surface', models.FloatField(blank=True, help_text='Surface en mètres carrés', null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Surface (m²)')),
                ('capacite', models.IntegerField(blank=True, help_text='Nombre de personnes pouvant occuper le bureau', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacité (personnes)')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Bureau',
                'verbose_name_plural': 'Bureaux',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_salle', models.CharField(choices=[('reunion', 'Réunion'), ('conference', 'Conférence'), ('pleniere', 'Plénière'), ('formation', 'Formation')], max_length=100, verbose_name='Type de salle')),
                ('nom', models.CharField(blank=True, default='', max_length=100, verbose_name='Nom')),
                ('niveau', models.CharField(blank=True, default='', help_text='Étage ou niveau de la salle', max_length=100, verbose_name='Niveau')),
                ('capacite', models.IntegerField(blank=True, help_text='Nombre maximum de personnes', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Capacité (personnes)')),
                ('surface', models.FloatField(blank=True, help_text='Surface en mètres carrés', null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Surface (m²)')),
                ('equipements', models.TextField(blank=True, default='', help_text='Liste des équipements disponibles', verbose_name='Équipements')),
                ('disponible', models.BooleanField(default=True, help_text='Indique si la salle est disponible', verbose_name='Disponible')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, default='', max_length=100, verbose_name='Nom du matériel')),
                ('description', models.TextField(blank=True, default='', help_text='Description détaillée du matériel', verbose_name='Description')),
                ('quantite', models.IntegerField(default=1, help_text="Nombre d'unités", validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité')),
                ('etat', models.CharField(choices=[('bon', 'Bon état'), ('moyen', 'État moyen'), ('mauvais', 'Mauvais état'), ('hs', 'Hors service'), ('autre', 'Autre')], default='bon', max_length=100, verbose_name='État')),
                ('numero_serie', models.CharField(blank=True, default='', help_text="Numéro de série ou d'inventaire", max_length=100, verbose_name='Numéro de série')),
                ('date_acquisition', models.DateField(blank=True, null=True, verbose_name="Date d'acquisition")),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, help_text="Prix d'achat unitaire", max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire (€)')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('bureau', models.ForeignKey(blank=True, help_text='Bureau où se trouve le matériel', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiels', to='patrimoine.bureau', verbose_name='Bureau')),
                ('salle', models.ForeignKey(blank=True, help_text='Salle où se trouve le matériel', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiels', to='patrimoine.salle', verbose_name='Salle')),
            ],
            options={
                'verbose_name': 'Matériel',
                'verbose_name_plural': 'Matériels',
                'ordering': ['nom'],
                'indexes': [models.Index(fields=['salle'], name='patrimoine__salle_i_500130_idx'), models.Index(fields=['bureau'], name='patrimoine__bureau__293a38_idx'), models.Index(fields=['etat'], name='patrimoine__etat_77c623_idx')],
            },
        ),
    ]
