# Generated by Django 6.0.2 on 2026-02-14 22:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimoine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='prix_unitaire',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Prix d'achat unitaire", max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire (GNF)'),
        ),
    ]
