# Generated by Django 6.0.2 on 2026-02-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimoine', '0002_alter_materiel_prix_unitaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='salle',
            name='picture',
            field=models.ImageField(blank=True, upload_to='', verbose_name='photo de la salle'),
        ),
    ]
